package net.nbc.thetestermod.item;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.nbc.thetestermod.TesterMod;
import net.nbc.thetestermod.block.ModBlocks;

import java.util.function.Supplier;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, TesterMod.MOD_ID);

    public static final Supplier<CreativeModeTab> THE_TESTER_ZONE_TAB = CREATIVE_MODE_TAB.register("the_tester_zone_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModItems.PURE_NIGHTMARITE.get()))
                    .title(Component.translatable("creativetab.testermod.the_tester_zone"))
                    .displayItems((itemDisplayParameters, output) -> {
                        output.accept(ModBlocks.CORRUPTED_OAK_LOG.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_CORRUPTED_OAK_LOG.get());
                        output.accept(ModBlocks.STRIPPED_CORRUPTED_OAK_WOOD.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_PLANKS.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_STAIRS.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_SLAB.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_FENCE.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_FENCE_GATE.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_DOOR.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_TRAPDOOR.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_BUTTON.get());
                        output.accept(ModItems.CORRUPTED_OAK_SIGN.get());
                        output.accept(ModItems.CORRUPTED_OAK_HANGING_SIGN.get());
                        output.accept(ModItems.CORRUPTED_OAK_BOAT.get());
                        output.accept(ModItems.CORRUPTED_OAK_CHEST_BOAT.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_LEAVES.get());
                        output.accept(ModBlocks.MYSTERIOUS_DUST_SLAB.get());
                        output.accept(ModBlocks.MYSTERIOUS_DUST_BLOCK.get());
                        output.accept(ModItems.MYSTERIOUS_DUST.get());

                        output.accept(ModItems.INDIGO_DUST.get());
                        output.accept(ModItems.INDIGO_BRICK.get());
                        output.accept(ModBlocks.INDIGO_BRICKS.get());
                        output.accept(ModBlocks.INDIGO_BRICK_STAIRS.get());
                        output.accept(ModBlocks.INDIGO_BRICK_SlAB.get());
                        output.accept(ModBlocks.INDIGO_BRICK_WALL.get());
                        output.accept(ModItems.MYSTERIOUS_STRING.get());
                        output.accept(ModItems.WOVEN_INDIGO_BRICK.get());
                        output.accept(ModItems.PURE_EYE.get());
                        output.accept(ModBlocks.PURIFIER_BLOCK.get());
                        output.accept(ModItems.IMPURE_EYE.get());
                        output.accept(ModBlocks.IMPURIFIER_BLOCK.get());
                        output.accept(ModItems.STRANGE_STICK.get());
                        output.accept(ModItems.PURE_STICK.get());
                        output.accept(ModItems.IMPURE_STICK.get());

                        output.accept(ModBlocks.NIGHTMARITE_ORE.get());
                        output.accept(ModBlocks.NIGHTMARITE_DEEPSLATE_ORE.get());
                        output.accept(ModBlocks.NIGHTMARITE_NETHER_ORE.get());
                        output.accept(ModBlocks.NIGHTMARITE_END_ORE.get());
                        output.accept(ModItems.NIGHTMARITE.get());
                        output.accept(ModItems.PURE_NIGHTMARITE.get());
                        output.accept(ModItems.IMPURE_NIGHTMARITE.get());
                        output.accept(ModItems.FALSE_NIGHTMARITE_INGOT.get());
                        output.accept(ModBlocks.FALSE_NIGHTMARITE_BLOCK.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_SWORD.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_PICKAXE.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_AXE.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_SHOVEL.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_HOE.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_HELMET.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_CHESTPLATE.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_LEGGINGS.get());
                        output.accept(ModItems.FALSE_NIGHTMARE_BOOTS.get());

                        output.accept(ModItems.NIGHTMARE_INGOT.get());
                        output.accept(ModItems.NIGHTMARE_NUGGET.get());
                        output.accept(ModBlocks.NIGHTMARE_BLOCK.get());
                        output.accept(ModBlocks.NIGHTMARE_STAIRS.get());
                        output.accept(ModBlocks.NIGHTMARE_SlAB.get());
                        output.accept(ModBlocks.NIGHTMARE_WALL.get());
                        output.accept(ModBlocks.NIGHTMARE_FENCE.get());
                        output.accept(ModBlocks.NIGHTMARE_FENCE_GATE.get());
                        output.accept(ModBlocks.NIGHTMARE_DOOR.get());
                        output.accept(ModBlocks.NIGHTMARE_TRAPDOOR.get());
                        output.accept(ModBlocks.NIGHTMARE_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.NIGHTMARE_BUTTON.get());
                        output.accept(ModBlocks.NIGHTMARE_LAMP.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_BLOCK.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_STAIRS.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_SlAB.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_WALL.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_FENCE.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_FENCE_GATE.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.REFINED_NIGHTMARE_BUTTON.get());

                        output.accept(ModItems.PURE_NIGHTMARE_SWORD.get());
                        output.accept(ModItems.PURE_NIGHTMARE_PICKAXE.get());
                        output.accept(ModItems.PURE_NIGHTMARE_AXE.get());
                        output.accept(ModItems.PURE_NIGHTMARE_SHOVEL.get());
                        output.accept(ModItems.PURE_NIGHTMARE_HOE.get());
                        output.accept(ModItems.PURE_NIGHTMARE_HAMMER.get());
                        output.accept(ModItems.NIGHTMARE_SWORD.get());
                        output.accept(ModItems.NIGHTMARE_PICKAXE.get());
                        output.accept(ModItems.NIGHTMARE_AXE.get());
                        output.accept(ModItems.NIGHTMARE_SHOVEL.get());
                        output.accept(ModItems.NIGHTMARE_HOE.get());
                        output.accept(ModItems.NIGHTMARE_HAMMER.get());
                        output.accept(ModItems.NIGHTMARE_HELMET.get());
                        output.accept(ModItems.NIGHTMARE_CHESTPLATE.get());
                        output.accept(ModItems.NIGHTMARE_LEGGINGS.get());
                        output.accept(ModItems.NIGHTMARE_BOOTS.get());
                        output.accept(ModItems.NIGHTEN_SMITHING_TEMPLATE.get());
                        output.accept(ModItems.NIGHTMARE_HORSE_ARMOR.get());

                        output.accept(ModBlocks.STORMITE_ORE.get());
                        output.accept(ModBlocks.STORMITE_DEEPSLATE_ORE.get());
                        output.accept(ModBlocks.STORM_NETHER_ORE.get());
                        output.accept(ModBlocks.STORM_END_ORE.get());
                        output.accept(ModItems.STORMITE.get());
                        output.accept(ModItems.PURE_STORMITE.get());
                        output.accept(ModItems.IMPURE_STORMITE.get());
                        output.accept(ModItems.FALSE_STORMITE_INGOT.get());
                        output.accept(ModBlocks.FALSE_STORMITE_BLOCK.get());
                        output.accept(ModItems.FALSE_STORM_SWORD.get());
                        output.accept(ModItems.FALSE_STORM_PICKAXE.get());
                        output.accept(ModItems.FALSE_STORM_AXE.get());
                        output.accept(ModItems.FALSE_STORM_SHOVEL.get());
                        output.accept(ModItems.FALSE_STORM_HOE.get());
                        output.accept(ModItems.FALSE_STORM_HELMET.get());
                        output.accept(ModItems.FALSE_STORM_CHESTPLATE.get());
                        output.accept(ModItems.FALSE_STORM_LEGGINGS.get());
                        output.accept(ModItems.FALSE_STORM_BOOTS.get());

                        output.accept(ModItems.STORM_INGOT.get());
                        output.accept(ModItems.STORM_NUGGET.get());
                        output.accept(ModBlocks.STORM_BLOCK.get());
                        output.accept(ModBlocks.STORM_STAIRS.get());
                        output.accept(ModBlocks.STORM_SlAB.get());
                        output.accept(ModBlocks.STORM_WALL.get());
                        output.accept(ModBlocks.STORM_FENCE.get());
                        output.accept(ModBlocks.STORM_FENCE_GATE.get());
                        output.accept(ModBlocks.STORM_DOOR.get());
                        output.accept(ModBlocks.STORM_TRAPDOOR.get());
                        output.accept(ModBlocks.STORM_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.STORM_BUTTON.get());
                        output.accept(ModBlocks.STORM_LAMP.get());
                        output.accept(ModItems.PURE_STORM_SWORD.get());
                        output.accept(ModItems.PURE_STORM_PICKAXE.get());
                        output.accept(ModItems.PURE_STORM_AXE.get());
                        output.accept(ModItems.PURE_STORM_SHOVEL.get());
                        output.accept(ModItems.PURE_STORM_HOE.get());
                        output.accept(ModItems.PURE_STORM_HAMMER.get());
                        output.accept(ModItems.STORM_SWORD.get());
                        output.accept(ModItems.STORM_PICKAXE.get());
                        output.accept(ModItems.STORM_AXE.get());
                        output.accept(ModItems.STORM_SHOVEL.get());
                        output.accept(ModItems.STORM_HOE.get());
                        output.accept(ModItems.STORM_HAMMER.get());
                        output.accept(ModItems.STORM_HELMET.get());
                        output.accept(ModItems.STORM_CHESTPLATE.get());
                        output.accept(ModItems.STORM_LEGGINGS.get());
                        output.accept(ModItems.STORM_BOOTS.get());
                        output.accept(ModItems.STORMEN_SMITHING_TEMPLATE.get());
                        output.accept(ModItems.STORM_HORSE_ARMOR.get());
                        output.accept(ModBlocks.PEDESTAL_BLOCK.get());
                        output.accept(ModItems.ENERGY_ORB.get());

                        output.accept(ModItems.STEELICHROME_PICKAXE.get());
                        output.accept(ModBlocks.STEELIUM_BLOCK.get());
                        output.accept(ModBlocks.STEELIUM_STAIRS.get());
                        output.accept(ModBlocks.STEELIUM_SlAB.get());
                        output.accept(ModBlocks.STEELIUM_WALL.get());
                        output.accept(ModBlocks.STEELIUM_DOOR.get());
                        output.accept(ModBlocks.STEELIUM_TRAPDOOR.get());
                        output.accept(ModBlocks.STEELIUM_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.STEELIUM_BUTTON.get());
                        output.accept(ModBlocks.STEELIUM_BARS.get());
                        output.accept(ModBlocks.SMOOTH_STEELIUM_BLOCK.get());
                        output.accept(ModBlocks.SMOOTH_STEELIUM_STAIRS.get());
                        output.accept(ModBlocks.SMOOTH_STEELIUM_SlAB.get());
                        output.accept(ModBlocks.SMOOTH_STEELIUM_WALL.get());
                        output.accept(ModBlocks.CHISELED_STEELIUM_BLOCK.get());
                        output.accept(ModBlocks.STEELIUM_CONSOLE.get());
                        output.accept(ModBlocks.STEELIUM_CORE.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_VERT.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_HORI.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_CORNER_BL.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_CORNER_BR.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_CORNER_TR.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_CORNER_TL.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_THREEWAY_L.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_THREEWAY_B.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_THREEWAY_R.get());
                        output.accept(ModBlocks.STEELIUM_ENERGY_TUBE_THREEWAY_T.get());
                        output.accept(ModBlocks.STEELIUM_LAMP.get());
                        output.accept(ModBlocks.STEELIUM_VAULT_BLOCK.get());
                        output.accept(ModBlocks.STEELIUM_VAULT_WALL.get());

                        output.accept(ModBlocks.NEPTOCHROME_BLOCK.get());
                        output.accept(ModBlocks.NEPTOCHROME_STAIRS.get());
                        output.accept(ModBlocks.NEPTOCHROME_SLAB.get());
                        output.accept(ModBlocks.NEPTOCHROME_WALL.get());
                        output.accept(ModBlocks.NEPTOCHROME_DOOR.get());
                        output.accept(ModBlocks.NEPTOCHROME_TRAPDOOR.get());
                        output.accept(ModBlocks.NEPTOCHROME_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.NEPTOCHROME_BUTTON.get());
                        output.accept(ModBlocks.NEPTOCHROME_BARS.get());
                        output.accept(ModBlocks.SMOOTH_NEPTOCHROME_BLOCK.get());
                        output.accept(ModBlocks.SMOOTH_NEPTOCHROME_STAIRS.get());
                        output.accept(ModBlocks.SMOOTH_NEPTOCHROME_SLAB.get());
                        output.accept(ModBlocks.SMOOTH_NEPTOCHROME_WALL.get());
                        output.accept(ModBlocks.CHISELED_NEPTOCHROME_BLOCK.get());
                        output.accept(ModBlocks.NEPTOCHROME_CONSOLE.get());
                        output.accept(ModBlocks.NEPTOCHROME_CORE.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_VERT.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_HORI.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_CORNER_BL.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_CORNER_BR.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_CORNER_TR.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_CORNER_TL.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_THREEWAY_L.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_THREEWAY_B.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_THREEWAY_R.get());
                        output.accept(ModBlocks.NEPTOCHROME_ENERGY_TUBE_THREEWAY_T.get());
                        output.accept(ModBlocks.NEPTOCHROME_LAMP.get());
                        output.accept(ModBlocks.NEPTOCHROME_VAULT_BLOCK.get());
                        output.accept(ModBlocks.NEPTOCHROME_VAULT_WALL.get());
                        output.accept(ModItems.STEELICHROME_KEYS.get());

                        output.accept(ModItems.REFINED_STEELICHROME_INGOT.get());
                        output.accept(ModItems.REFINED_STEELICHROME_NUGGET.get());
                        output.accept(ModBlocks.STEELICHROME_BLOCK.get());
                        output.accept(ModBlocks.STEELICHROME_STAIRS.get());
                        output.accept(ModBlocks.STEELICHROME_SLAB.get());
                        output.accept(ModBlocks.STEELICHROME_WALL.get());
                        output.accept(ModBlocks.STEELICHROME_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.STEELICHROME_BUTTON.get());
                        output.accept(ModBlocks.STEELICHROME_BARS.get());
                        output.accept(ModBlocks.SMOOTH_REFINED_STEELICHROME_BLOCK.get());
                        output.accept(ModBlocks.SMOOTH_REFINED_STEELICHROME_STAIRS.get());
                        output.accept(ModBlocks.SMOOTH_REFINED_STEELICHROME_SLAB.get());
                        output.accept(ModBlocks.SMOOTH_REFINED_STEELICHROME_WALL.get());
                        output.accept(ModBlocks.CHISELED_REFINED_STEELICHROME_BLOCK.get());
                        output.accept(ModItems.REFINED_STEELICHROME_SWORD.get());
                        output.accept(ModItems.REFINED_STEELICHROME_PICKAXE.get());
                        output.accept(ModItems.REFINED_STEELICHROME_AXE.get());
                        output.accept(ModItems.REFINED_STEELICHROME_SHOVEL.get());
                        output.accept(ModItems.REFINED_STEELICHROME_HOE.get());
                        output.accept(ModItems.REFINED_STEELICHROME_HELMET.get());
                        output.accept(ModItems.REFINED_STEELICHROME_CHESTPLATE.get());
                        output.accept(ModItems.REFINED_STEELICHROME_LEGGINGS.get());
                        output.accept(ModItems.REFINED_STEELICHROME_BOOTS.get());

                        output.accept(ModItems.ALIEN_SPAWN_EGG.get());
                        output.accept(ModItems.ARMORED_ALIEN_SPAWN_EGG.get());
                        output.accept(ModItems.TESTER_SPAWN_EGG.get());
                        output.accept(ModItems.GOLDEN_MELON_SLICE.get());
                        output.accept(ModBlocks.GOLDEN_MELON_BLOCK.get());
                        output.accept(ModItems.WHITE_CARROT.get());
                        output.accept(ModItems.GLISTERING_CARROT.get());
                        output.accept(ModItems.CRIMSON_BLUE_BERRIES.get());
                        output.accept(ModItems.DEVILS_SNATH.get());
                        output.accept(ModItems.DEVILS_BLADE.get());
                        output.accept(ModItems.DEVILSKNIFE.get());
                        output.accept(ModItems.THROWING_KNIFE.get());
                        output.accept(ModBlocks.RED_GAMING_CHAIR.get());
                        output.accept(ModBlocks.BLUE_GAMING_CHAIR.get());
                        output.accept(ModItems.CHISEL.get());
                        output.accept(ModBlocks.CORRUPTED_OAK_SAPLING.get());
                        output.accept(ModItems.VOID_MUSIC_DISK.get());
                    }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TAB.register(eventBus);
    }
}
